apiVersion: v1
kind: PersistentVolume
metadata:
 name: "pg-pv-volume"
spec:
 capacity:
   storage: 3Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Recycle
 awsElasticBlockStore:
   volumeID: vol-0108f87f072877284 # Change here
   fsType: ext4